AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SchachParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonRekognitionFullAccess
        - AmazonS3ReadOnlyAccess
      Events:
        UploadApi:
          Type: Api
          Properties:
            Path: /upload
            Method: post